
name: 'snowplow_normalize'
version: '0.1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
docs-paths: ["docs"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
