
name: 'snowplow_composable_events'
version: '0.0.1'
config-version: 2

profile: 'default'

model-paths: ["models"]
docs-paths: ["docs"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
